export const SAVE_SESSION = "SAVE_SESSION";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_PROFILE_INFO = "GET_USER_PROFILE_INFO";
export const EDIT_USER_PROFILE_INFO = "EDIT_USER_PROFILE_INFO";
export const GET_USER_FOLLOWERS = "GET_USER_FOLLOWERS";
export const GET_USER_FOLLOWING = "GET_USER_FOLLOWING";
export const GET_USER_TWEETS = "GET_USER_TWEETS";
export const GET_FOLLOW_TWEETS = "GET_FOLLOW_TWEETS";
export const GET_COMMENTS = "GET_COMMENTS";

export const POST_USER_TWEETS = "POST_USER_TWEETS";
export const POST_COMMENT = "POST_COMMENT";
export const POST_LIKE_TWEET = "POST_LIKE_TWEET";
export const POST_LIKE_COMMENT = "POST_LIKE_COMMENT";

export const DELETE_TWEET = "DELETE_TWEET";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const REMOVE_LIKE_TWEET = "REMOVE_LIKE_TWEET";
export const REMOVE_LIKE_COMMENT = "REMOVE_LIKE_COMMENT";

export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
