export const GET_USER_PROFILE_INFO = "GET_USER_PROFILE_INFO";
export const GET_USER_FOLLOWERS = "GET_USER_FOLLOWERS";
export const GET_USER_FOLLOWING = "GET_USER_FOLLOWING";
export const GET_USER_TWEETS = "GET_USER_TWEETS";
export const POST_USER_TWEETS = "POST_USER_TWEETS";
export const POST_LIKE_TWEET = "POST_LIKE_TWEET";
export const REMOVE_LIKE_TWEET = "REMOVE_LIKE_TWEET";
